export const phonesList = [
  {
    name: "iPhone 13 Pro",
    image: "https://m.media-amazon.com/images/I/61eDXs9QFNL._AC_SX679_.jpg",
    rating: 4.5,
    price: 920,
    id: 0,
    specifications: {
      display: "6.1-inch Super Retina XDR",
      processor: "A15 Bionic",
      RAM: "6 GB",
      storage: "128 GB",
      camera: "Triple 12 MP",
      battery: "Li-Ion 3095 mAh",
    },
  },
  {
    name: "Samsung  S21",
    image: "https://m.media-amazon.com/images/I/61-QMCHyUES._AC_SL1000_.jpg",
    rating: 4.3,
    price: 239,
    id: 1,
    specifications: {
      display: "6.2-inch Dynamic AMOLED 2X",
      processor: "Exynos 2100",
      RAM: "8 GB",
      storage: "128 GB",
      camera: "Triple 12 MP",
      battery: "Li-Ion 4000 mAh",
    },
  },
  {
    name: "Google Pixel 6",
    image: "https://m.media-amazon.com/images/I/61ruKkvVIxL._AC_SL1000_.jpg",
    rating: 4.8,
    price: 259,
    id: 2,
    specifications: {
      display: "6.4-inch FHD+ AMOLED",
      processor: "Google Tensor",
      RAM: "8 GB",
      storage: "128 GB",
      camera: "Dual 50 MP",
      battery: "Li-Po 4614 mAh",
    },
  },
  {
    name: "OnePlus 9 Pro",
    image: "https://m.media-amazon.com/images/I/61smwbhzBML._AC_SL1500_.jpg",
    rating: 4.6,
    price: 320,
    id: 3,
    specifications: {
      display: "6.7-inch Fluid AMOLED",
      processor: "Snapdragon 888",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Quad 48 MP",
      battery: "Li-Po 4500 mAh",
    },
  },
  {
    name: "Xiaomi Mi 11",
    image: "https://m.media-amazon.com/images/I/616O4heTezL._AC_SL1423_.jpg",
    rating: 4.4,
    price: 420,
    id: 4,
    specifications: {
      display: "6.81-inch AMOLED",
      processor: "Snapdragon 888",
      RAM: "8 GB",
      storage: "128 GB",
      camera: "Triple 108 MP",
      battery: "Li-Po 4600 mAh",
    },
  },
  {
    name: "Samsung Note 20 Ultra",
    image: "https://m.media-amazon.com/images/I/817aOXLoNpL._AC_SL1500_.jpg",
    rating: 4.7,
    price: 620,
    id: 5,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "OPPO Reno8 Pro 5G",
    image: "https://m.media-amazon.com/images/I/61IpMhWFC+L._AC_SL1500_.jpg",
    rating: 4.7,
    price: 700,
    id: 6,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "OPPO Reno8 Pro 5G",
    image: "https://m.media-amazon.com/images/I/514aaPyf+ZL._AC_SL1000_.jpg",
    rating: 4.7,
    price: 250,
    id: 7,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "Oppo Reno 7 5G Dual",
    image: "https://m.media-amazon.com/images/I/41PDgqjXAZL._AC_SX679_.jpg",
    rating: 4.7,
    price: 410,
    id: 8,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "Apple iPhone 14 Pro Max",
    image: "https://m.media-amazon.com/images/I/51iJx7YWDOL._AC_SL1000_.jpg",
    rating: 4.7,
    price: 1240,
    id: 9,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "Apple iPhone 11 Pro",
    image: "https://m.media-amazon.com/images/I/81LmL94PUvS._AC_SL1500_.jpg",
    rating: 4.7,
    price: 540,
    id: 10,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "Apple iPhone 12 Pro",
    image: "https://m.media-amazon.com/images/I/61V5eKGWmYL._AC_SL1500_.jpg",
    rating: 4.7,
    price: 540,
    id: 11,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },

  {
    name: "iPhone 13 Mini",
    image: "https://m.media-amazon.com/images/I/61VByDni+vL._AC_SL1500_.jpg",
    rating: 4.7,
    price: 655,
    id: 13,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "Samsung  S21 5G",
    image: "https://m.media-amazon.com/images/I/61jYjeuNUnL._AC_SL1000_.jpg",
    rating: 4.7,
    price: 555,
    id: 14,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "SAMSUNG  S23",
    image: "https://m.media-amazon.com/images/I/718LuUVEOZL._AC_SL1500_.jpg",
    rating: 4.7,
    price: 1455,
    id: 15,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "Samsung  S21 5G",
    image: "https://m.media-amazon.com/images/I/718LuUVEOZL._AC_SL1500_.jpg",
    rating: 4.7,
    price: 1455,
    id: 16,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "OPPO Reno 8",
    image: "https://m.media-amazon.com/images/I/51JN83L+14L._AC_SL1000_.jpg",
    rating: 4.7,
    price: 1455,
    id: 17,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "Oppo Reno 6 Pro 5G",
    image: "https://m.media-amazon.com/images/I/41ljHDD969L._AC_.jpg",
    rating: 4.7,
    price: 1455,
    id: 18,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "OnePlus 11 5G",
    image: "https://m.media-amazon.com/images/I/71jvbxyQ2TL._AC_SL1500_.jpg",
    rating: 4.7,
    price: 1455,
    id: 19,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "Oppo Find X5 Pro 5G",
    image: "https://m.media-amazon.com/images/I/71QmFJCJ-ML._AC_SL1500_.jpg",
    rating: 4.7,
    price: 1455,
    id: 20,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "OnePlus Nord N30 5G",
    image: "https://m.media-amazon.com/images/I/616uMtIWiiL._AC_SL1500_.jpg",
    rating: 4.7,
    price: 1455,
    id: 21,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "Realme GT 2 Pro 5G ",
    image: "https://m.media-amazon.com/images/I/51mHcXbI+gL._AC_.jpg",
    rating: 4.7,
    price: 1455,
    id: 22,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "OnePlus Nord N30 5G",
    image: "https://m.media-amazon.com/images/I/616uMtIWiiL._AC_SL1500_.jpg",
    rating: 4.7,
    price: 1455,
    id: 23,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
  {
    name: "OPPO Reno 8",
    image: "https://m.media-amazon.com/images/I/616uMtIWiiL._AC_SL1500_.jpg",
    rating: 4.7,
    price: 1455,
    id: 24,
    specifications: {
      display: "6.9-inch Dynamic AMOLED 2X",
      processor: "Exynos 990",
      RAM: "12 GB",
      storage: "256 GB",
      camera: "Triple 108 MP",
      battery: "Li-Ion 4500 mAh",
    },
  },
];
